<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CGJKOVL" ignored="0" name="ITeration5" tests="4" failures="2" timestamp="2021-01-10T16:22:00 IST" time="46.381" errors="0">
  <testcase name="launch" time="21.278" classname="tests.LoginTestWithXml"/>
  <testcase name="userIdTesting" time="3.179" classname="tests.LoginTestWithXml">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at tests.LoginTestWithXml.userIdTesting(LoginTestWithXml.java:108)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- userIdTesting -->
  <testcase name="passwordTesting" time="20.78" classname="tests.LoginTestWithXml">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at tests.LoginTestWithXml.passwordTesting(LoginTestWithXml.java:181)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- passwordTesting -->
  <testcase name="closeSite" time="0.989" classname="tests.LoginTestWithXml"/>
</testsuite> <!-- ITeration5 -->
